name: Pull Request auto-merge

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    uses: jiamiao442/.github/.github/workflows/pr-auto-merge.yml@main
    with:
      allowed-author: eclipse-temurin-bot
